config/routes.rb
Rails.application.routes.draw do
    resources :wikis
    resources :charges, only: [:new, :create, :destroy]

    devise_for :users
    resources :users, only: [:show] do
        patch '/downgrade', to: 'users#downgrade'
    end

    resources :wikis do
        resources :collaborators, only: [:index, :new, :create]
    end
    get 'about' => 'welcome#about'
    root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :wikis, dependent: :destroy
    has_many :collaborations
    has_many :shared_wikis, through: :collaborations, source: :wiki
    before_save { self.email = email.downcase if email.present? }
    after_initialize :init
    enum role: [:member, :admin, :premium]

    def init
        self.role ||= :member
  end
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user
  scope :visible_to, -> (user) { user.role == 'premium' || user.role == 'admin' ? all : where(private: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    private

    def user_not_authorized
        flash[:alert] = 'You are not authorized to do that.'
        redirect_to root_path
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
        @stripe_btn_data = {
            key: Rails.configuration.stripe[:publishable_key].to_s,
            description: "Upgrade to Premium - #{current_user.email}",
            amount: 15_00
        }
    end

    def create
        # Creates a Stripe Customer object, for associating
        # with the charge
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )

        # Where the real magic happens
        charge = Stripe::Charge.create(
            customer: customer.id, # Note -- this is NOT the user_id in your app
            amount: 15_00,
            description: "Upgrade to Premium - #{current_user.email}",
            currency: 'usd'
        )

        flash[:notice] = "Thanks for your payment, #{current_user.email}!"
        current_user.premium!
        redirect_to wikis_path(current_user) # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
   end

    
end

private

class Amount
    def default
        15_00
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    def index
        @wiki = Wiki.find(params[:wiki_id])
        @collaborators = @wiki.collaborators.all
    end

    def new
        @wiki = Wiki.find(params[:wiki_id])
        authorize(Collaboration.new)
    end

    def create
        wiki = Wiki.find(params[:wiki_id])
        collaborators = []
        wiki.collaborators.destroy_all
        if params[:collaborators]
            params[:collaborators].each do |c|
                collaborators << {
                    wiki_id: wiki.id,
                    user_id: c
                }
            end
            Collaboration.create(collaborators)
      end

        redirect_to wiki_collaborators_path(wiki)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end

    def downgrade
        user = current_user

        if user.role == 'premium'
            user.role = 0

            if user.save
                make_public
                flash[:notice] = 'Your account has been changed to a Standard account. Feel free to upgrade at any time!'
                redirect_to root_path
            else
                flash[:alert] = 'Account downgrade failed. Please try again at another time.'
                redirect_to root_path
            end
        else
            flash[:alert] = 'Your account is already Standard and cannot be downgraded, or you are an Admin.'
        end
    end

    def make_public
        wikis = Wiki.where(user_id: current_user.id)
        wikis.update_all(private: false)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    skip_before_filter :authenticate_user!, only: [:index, :show, :edit, :update]

    def index
        @wikis = policy_scope(Wiki)
    end

    def show
        @wiki = Wiki.find(params[:id])
        unless @wiki.private == false || current_user.role == 'admin' || current_user.role == 'premium'
            flash[:alert] = 'You must upgrade your account to view private Wiki entries.'
            redirect_to root_path
    end
    end

    def new
        @wiki = Wiki.new
    end

    def create
        @wiki = Wiki.create(wiki_params)
        @wiki.user = current_user

        if @wiki.save
            flash[:notice] = 'Wiki was saved.'
            redirect_to @wiki
        else
            flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
            render :new
        end
    end

    def edit
        @wiki = Wiki.find(params[:id])
    end

    def update
        @wiki = Wiki.find(params[:id])
        authorize @wiki
        @wiki.assign_attributes(wiki_params)

        if @wiki.save
            flash[:notice] = 'Wiki was updated'
            redirect_to @wiki
        else
            flash.now[:alert] = 'Error saving wiki. Please try again.'
            render :edit
        end
    end

    def destroy
        @wiki = Wiki.find(params[:id])

        if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to wikis_path
        else
            flash.now[:alert] = 'There was an error deleting the wiki'
            render :show
        end
    end

    private

    def wiki_params
        params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
        options = {
            fenced_code_blocks: true,
            no_intra_emphasis: true,
            autolink: true,
            strikethrough: true,
            lax_html_blocks: true,
            superscript: true
        }
        Redcarpet::Markdown.new(renderer, options).render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def user_can_upgrade?(user)
        current_user == user && current_user.role == 'member'
     end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<h4>Click the button!</h4>

<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>"></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>All Collaborators for
    <%= @wiki.title %>
    Wiki
</h1>

<ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborators %></ul>

<p><%= link_to "Return to Wiki", wiki_path(@wiki), class: 'btn btn-success' %></p>

app/views/collaborators/new.html.erb
<h2>Add collaborators to <%= @wiki.title %>:</h2>

<%= form_tag(wiki_collaborators_path(wiki_id: @wiki), method: :post) do %>
    <table class="users_table">
        <tr>
            <th>User</th>
            <th>Give Access?</th>
        </tr>
        <% User.all.each do |user| %>
            <tr>
                <td><%= user.email %></td>
                <td><%= check_box_tag('collaborators[]', user.id, @wiki.collaborators.include?(user), {multiple: true}) %></td>
            </tr>
        <% end %>
    </table>
    <p><%= submit_tag("Save", class: 'btn btn-success', data: {confirm: "Are you sure you want to add/remove these collaborators?"}) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Blocipedia</title>
        <meta name="viewport" content="width=device-width initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
            <ul class="nav nav-tabs">
                <li><%= link_to "Blocipedia", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <div class="pull-right user-info">
                    <% if user_signed_in? %>
                    Signed in as:
                    <strong><%= link_to current_user.email, user_path(current_user) %></strong>

                    <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %>
                    -
                    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
                <% else %>
                    <%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link' %>
                    -
                    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
                    <% end %>
                </div>
            </ul>

            <% if flash[:notice] %>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
            </div>
            <% elsif flash.now[:alert] %>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash.now[:alert] %>
            </div>
            <% elsif flash[:alert] %>
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
            </div>
            <% end %>

            <%= yield %>
        </div>

    </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email if @user.email%></h1>
<h3>User type:
    <%= @user.role %></h3>

<!-- Btn should only appear is standard member looking at their own profile -->
<% if user_can_upgrade?(@user) %>
<%= link_to "Upgrade to Premium Account!", new_charge_path, class: 'btn btn-success' %>
<% end %>

<% if @user.role == 'premium' %>
    <%= link_to "Downgrade", user_downgrade_path(current_user), method: :patch, class: 'btn btn-default' %>
  <% end %></p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Blocipedia: Social, Markdown Wikis</h1>
    <h3>Create and share Markdown Wikis</h3>
    <p>
        <% if !user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-success' %>
        <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-default' %>
        <% end %>
    </p>
</div>

<div class="row">
    <div class="col-md-6">
        <p>Create as many public wikis as you want!</p>
        <span class="glyphicon glyphicon-fire"></span><br>
        Free Plan
    </div>
    <div class="col-md-6">
        <p>Create private wikis!</p>
        <span class="glyphicon glyphicon-euro"></span><br>
        Premium Plan
    </div>
</div>

app/views/wikis/_collaborator.html.erb
<li><%= link_to collaborator.email, user_path(collaborator) %></li>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @wiki do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% end %>
    </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% @wikis.each do |wiki| %>
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
        </h4>
    </div>
</div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
    <div class="col-md-3">
        <p>Guidelines for Wikis</p>
        <ul>
            <li>Make sure it has a logic.</li>
            <li>Be aware of sensitive material.</li>
            <li>Post only constructive things.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @wiki do |f| %>
        <div class="form-group">
            <%= f.label :title %>

            <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
        </div>
        <% if current_user.admin? || current_user.premium? %>

        <div class="form-group">

            <%= f.label :private, class: 'checkbox' do %>

            <%= f.check_box :private %>
            Private wiki 
            <% end %>

        </div>

        <% end %>
        <div class="form-group">

            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% end %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1>
    <%= @wiki.title %>
    <br>
    <small>
        submitted
        <%= time_ago_in_words(@wiki.created_at) %>
        ago
    </small>
    <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-primary' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
</h1>
<p><%= markdown(@wiki.body) %></p>
<p>Created by:
    <%= @wiki.user.email %></p>
<div>
    <% if @wiki.private %>
    <h4>Collaborators:</h4>
    <p><%= link_to "Add/Remove collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-default' %></p>
    <ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborators%></ul>
    <% end %>
</div>

<%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>